version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: nissan_erp_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./nissan_erp.db
    # Utilizamos .env de backend si existe
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nissan_erp_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobreescribir el node_modules del contenedor con el local
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
